openapi: 3.0.3
info:
  title: SWVS HA Microservice Architecture - Measurement Data API
  description: API Documentation for Measurement Data (Messdaten)
  version: 1.0.0

tags:
  - name: Measurements
    description: Measurement Data operations.

