openapi: 3.0.3
info:
  title: SWVS HA Raspberry Pi and MQTT - Measurement Data API
  description: API Documentation for Measurement Data (Messdaten)
  version: 1.0.0

tags:
  - name: Measurements
    description: Measurement Data operations.

path:
  /measurements:
    get:
      tags:
        - measurements
      summary: Get Measurements
      description: Fetches all recorded measurements from te database.
      operationId: getMeasurements
      parameters:
        - name: measurementId
          in: path
          description: The ID of the measurement
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Measurement retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Unique ID of the measurement.
                    example: 101
                  sensorID:
                    type: integer
                    description: Sensor ID.
                    example: 1
                  timestamp:
                    type: string
                    format: date-time
                    description: Time of the measurement.
                    example: "2024-10-11T10:20:30Z"
                  temperature:
                    type: number
                    format: float
                    description: Temperature value in Celsius.
                    example: 22.5
                  humidity:
                    type: number
                    format: float
                    description: Humidity percentage.
                    example: 55.5
        '404':
          description: Measurement not found.